### ISSUE TITLE
Тип местности/погоды

### ISSUE THREAD

**Issue by bamx23** [kswaldemar/rewind-viewer#14]
Не очень понятно, можно ли отрисовать одновременно и лес, и облака, например?
Судя по коду, такое не возможно. Но текстуры, по наличию альфы, подходящие.

**Comment by kswaldemar** [comment]
Можно вызвать несколько команд на отрисовку земли/погоды с одинаковыми координатами. 
Порядок отрисовки [соответствует порядку тут](https://github.com/kswaldemar/rewind-viewer/blob/4d12fb4df38334f9eb68fdd986a3a07201d96faf/src/viewer/Frame.h#L34-L40). Первым рисуется лес, последним облака.
Также отмечу, что передавать погоду следует один раз, она автоматически будет отрисовываться каждый тик.

**Comment by bamx23** [comment]
Только погоду передавать один раз или местность тоже?

**Comment by kswaldemar** [comment]
И погоду и местность достаточно передать один раз

**Comment by bamx23** [comment]
Отлично, спасибо
