### ISSUE TITLE
Ускоренная промотка

### ISSUE THREAD

**Issue by stalkermustang** [kswaldemar/rewind-viewer#16]
Если остается меньше 20 тиков(как я понял, по столько мотает за одно нажатие крайняя левая и правая кнопки), то приходится мотать по одному тику. Можно сделать проверку на близость к границе промотки и двигать "историю" на min(n, 20) тиков, чтобы можно было за одной нажатие откатиться с 16 на 0 тик.

**Comment by kswaldemar** [comment]
То есть нажатие ускоренной перемотки назад на 16 фрейме не приводит к переходу в 0 фрейм?
Это не сложно поправить. Сейчас можно использовать стрелки на клавиатуре или прямой переход на нужный фрейм.

**Comment by stalkermustang** [comment]
не приводит, скачет на -4 и тут же на 16.
Можно, но есть же кнопка, тем более что поправить легко =) А как прямо на фрейм попасть?

**Comment by kswaldemar** [comment]
ctrl+click по слайдеру фреймов или сочетанием клавиш, если версия из последнего мастера. Все сочетания описаны в хелпе.
