### ISSUE TITLE
Alpha channel support

### ISSUE THREAD

**Issue by olsh** [kswaldemar/rewind-viewer#18]
At the moment if I send the following command `{"type": "circle", "x": 50, "y": 50, "r": 20.54, "color": 855572480}` with the color `{Name=32ff0000, ARGB=(50, 255, 0, 0)}` (red with transparency) the viewer just ignores the alpha part.
![image](https://user-images.githubusercontent.com/3613592/32724996-72661b8a-c884-11e7-8245-41b94129f3e2.png)

Is it possible to add alpha channel support?

**Comment by kswaldemar** [comment]
Hi. It is possible, but transparency imply drawing order support. I'm currently working on that, assume it will be completed before week-end. Not so much work, but I'm pretty busy at the moment.

**Comment by kswaldemar** [comment]
New version just launched. Check out transparency support

**Comment by olsh** [comment]
Works as expected, I think the issue can be closed out.
Thank you! 👍
