### ISSUE TITLE
Draw custom text at coordinates

### ISSUE THREAD

**Issue by SHaaD94** [kswaldemar/rewind-viewer#19]
It would be really great to have opportunity to draw custom short strings by coordinates.

Is where any chance you'll have time for this?

**Comment by kswaldemar** [comment]
If you could just describe use case for such thing? There is already user message and popup messages with units info. I think plain text on field will be noisy and hard to read

**Comment by SHaaD94** [comment]
Exact use case is visualizing weights of nodes of potential field

**Comment by kswaldemar** [comment]
You may use different color intensity for that, there is support for alpha channel in latest versions. 
Anyway correct text rendering with scaling right on field requires very much efforts, including manual true type rendering engine. 
Simple solution may be to show arbitrary information in popup window, when mouse hovering particular region. But seems not so useful for me, though.

**Comment by SHaaD94** [comment]
Yeah, i am already doing that but when you need an absolute values, colors are pretty useless. 
Actually, solution with popup menu, containing custom parameters sounds good for me.

**Comment by kswaldemar** [comment]
Ok, I think this feature may fit with current architecture. Unfortunately I really don't have much time at the moment.
If someone interested in implementing such feature, I'll be happy to help.
