### ISSUE TITLE
Некорректная работа масштабирования

### ISSUE THREAD

**Issue by deniskolsanov** [kswaldemar/rewind-viewer#25]
Если убрать фокус с viewer'а, а затем поскролить не фокусируясь на окне, то координаты  уходят в бесконечность http://recordit.co/jA7DT6GIKq

**Comment by Karloid** [comment]
Тоже натыкался

**Comment by kswaldemar** [comment]
Сделал обновление окна, только когда оно в фокусе, должно помочь с проблемой скролла.

**Comment by Karloid** [comment]
Еще не тестил, 
но главный прикол в том что в мак оси можно посылать эвенты скролла когда окно не в фокусе, 
надо координаты курсора проверять на адекватность или что в этом духе

**Comment by kswaldemar** [comment]
Проверьте на mac os новую версию. Сейчас неактивное окно не должно реагировать на скролл и потреблять процессорное время.

**Comment by Karloid** [comment]
Проверил на macOS вроде все так и есть, отрисовка останавливается когда не в фокусе. 
побочный эффект небольшой - если скроллить окно когда оно не в фокусе, а затем зафокусировать его произойдет мгновенная смена масштаба

**Comment by deniskolsanov** [comment]
Работает, но простой sleep(100) похож на костыль, когда я переключаюсь между окнами, я же не нажимаю на паузу, а она ставится...

И еще:
constexpr static size_t FACILITY_LAYER = 0;
стоит поставить больше нуля, иначе нельзя нарисовать примитивы не заслонив постройки.

**Comment by kswaldemar** [comment]
Отключение отрисовки неактивного окна сделано для того, чтобы впустую не нагружать процессор. Подразумевается, что если визуализатором пользуются, то окно активно.

Поменять слой для построек можно, но действительно ли надо что-то рисовать под постройками?

**Comment by Karloid** [comment]
Мне норм как сейчас работает. И в плане не активного окна. И в плане отрисовки построек

**Comment by deniskolsanov** [comment]
Я пп рисую.
![screenshot_114](https://user-images.githubusercontent.com/3995683/33497688-bda9fe86-d6df-11e7-8fae-0021e9fdba9e.png)
Сейчас подумал... а ведь действительно над зданиями можно и не рисовать квадрат просто, или альфу в 0.5 установить

**Comment by Karloid** [comment]
Рекомендую все квадраты с альфой рисовать, что бы видеть погоду и почву

**Comment by kswaldemar** [comment]
Закрываю, проблема не повторяется. Если будут проблемы, переоткроем
