### ISSUE TITLE
How to use line break in Message() function? (Answer "\\n")

### ISSUE THREAD

**Issue by Savidiy** [kswaldemar/rewind-viewer#28]
Привет. Если я использую для перевода строки "\n", то сообщение не выводится. Какой перевод строки надо использовать в функции Message()?

Hi. If I used "\n" line break, message didn't out. What line break used in Message() function?

![default](https://user-images.githubusercontent.com/4676406/32938828-866d50dc-cb8e-11e7-9b0d-44138ed0afee.png)

**Comment by Karloid** [comment]
Попробуй отправлять "\\n"

**Comment by Savidiy** [comment]
Спасибо. Как я понял там самостоятельно выделяются из текста спецсимволы. Поэтому я использую Message("Hello \\\\n world"); и получаю перевод строки по середине, как и хотел. \\\\t делает табуляцию.

**Comment by Karloid** [comment]
все дело в том что сообщения отправляются в формате lson и например с++ и джава клиенты не экранируют строку отправляемую через message, и при появлении там всяких \n или " все ломается. Соответственно через message можно делать инъекции джсона : D

**Comment by kswaldemar** [comment]
В C++ клиенте это фича, строка парсится `snprintf` перед отправкой, чтобы можно было писать запросы вида `message("My pos %lf, %lf\\n", my_x, my_y)`. Поэтому нужно двойное экранирование

**Comment by kswaldemar** [comment]
Думаю можно закрыть issue, вопрос разрешен, а те кто столкнуться в дальнейшем смогут найти ответ поиском.
