### ISSUE TITLE
Некорректная работа на retina

### ISSUE THREAD

**Issue by Karloid** [kswaldemar/rewind-viewer#30]
![image](https://user-images.githubusercontent.com/2398460/32985010-a269fad6-ccc1-11e7-941d-17c8b6d2cdec.png)
координаты курсора неправильно пересчитываются, влияет и на зум и на наведение на юнита для показа попапа

**Comment by kswaldemar** [comment]
https://github.com/kswaldemar/rewind-viewer/blob/master/src/cgutils/Camera.cpp#L64
Попробуй поменять на `glfwGetWindowSize`

**Comment by Karloid** [comment]
![image](https://user-images.githubusercontent.com/2398460/32994125-20e32a2e-cd74-11e7-9e5d-c55d10cc57e1.png)
да это фиксит проблему
