### ISSUE TITLE
Feature request: Поддержка зданий

### ISSUE THREAD

**Issue by Karloid** [kswaldemar/rewind-viewer#33]
После первого раунда было бы здорово иметь возможность показывать здания с помощью **type**, вроде **livingunit**

**Comment by kswaldemar** [comment]
Изначально была такая задумка, даже текстурки подготовил :slightly_smiling_face:
Сейчас функционал можно сделать вручную - поставить прямоугольник и выводить любую информацию через popup.
На неделе сделаю отдельным примитивом.

**Comment by Karloid** [comment]
супер, очень ждем

**Comment by kswaldemar** [comment]
Реализовано в 1.3
