### ISSUE TITLE
Проблема с запуском - 0xc00007b

### ISSUE THREAD

**Issue by dbf256** [kswaldemar/rewind-viewer#40]
После переустановки Win7 перекачал revindviewer 1.3, при запуске выдается
Application popup: rewindviewer.exe - Application Error : The application was unable to start correctly (0xc000007b). Click OK to close the application. 
Каталог ресурсов рядом с exe, логов не создается.
Поискал немного по этой ошибке, переставил Microsoft Visual C++ Redistributable, Direct X, драйвер видеокарты, но никаких улучшений. Я так понимаю, что для запуска чего-то еще из библиотек не требуется?

**Comment by kswaldemar** [comment]
Для работы под windows требуется только opengl, все остальное устанавливается из репозитория. 
Если файлы логов вообще не создаются, то до инициализации дело не доходит. Какой версии Microsoft Visual C++ Redistributable? Бинарник собран в 2015 студии, полагаю для работы нужен c++ redist 2015.

**Comment by dbf256** [comment]
Был установлен для 2008 и 2017, поставил для 2015 версии 14.0.23026, но ошибка не поменялась.

**Comment by kswaldemar** [comment]
Redist поставлены для 32х бит и 64? Скорее всего собранный бинарник 32х битный, точно не помню. Гугл внятной информации по этой проблеме не дает, видимо нужно доставить каких-то системных пакетов.
Учитывая что больше ни у кого такой проблемы не наблюдалась, думаю самым простым решением будет собрать из исходников. Для этого нужна [Visual Studio 2015](https://www.microsoft.com/ru-ru/SoftMicrosoft/vs2015ExpressforW10.aspx) и cmake. В Readme есть инструкции по сборке.

**Comment by dbf256** [comment]
Точно, спасибо! С x86 заработало, добавил небольшой комментарий в readme: https://github.com/kswaldemar/rewind-viewer/pull/41
