### ISSUE TITLE
Heap corruption - after close attached LocalRunner

### ISSUE THREAD

**Issue by Pro100AlexHell** [kswaldemar/rewind-viewer#48]
Я сделал билд под windows 7, в visual studio 2015.
Запускаю Debug\rewindviewer.exe
запускаю LocalRunner.py который по socket создает соединение, передает игровые тики
смотрю в rewindviewer.exe - все отображается.
При закрытии LocalRunner.py - в rewindviewer.exe происходит краш
https://prnt.sc/opmq5t

каждый раз воспроизводится - при закрытии LocalRunner.py
т.е видимо при close сокета
пробовал смотреть логи
rewindviewer.log

rewindviewer-debug.log
там вот такое Один раз

> 2019-08-07 18:49:56.295 (   0.326s) [main thread     ]               main.cpp:145      0| Create network protocol handler: working with JSON protocol
> 2019-08-07 18:49:56.295 (   0.326s) [main thread     ]               main.cpp:150      0| Start networking thread
> 2019-08-07 18:49:56.297 (   0.329s) [                ]        NetListener.cpp:35       0| NetClient:: Start listening
> 2019-08-07 18:49:56.297 (   0.329s) [main thread     ]               main.cpp:166      0| Start render loop
> 2019-08-07 18:49:59.661 (   3.692s) [main thread     ]        NetListener.cpp:56       0| Stopping network listening
> 2019-08-07 18:49:59.661 (   3.693s) [main thread     ]               main.cpp:202      0| Save config file rewindviewer.cfg
> 2019-08-07 18:49:59.662 (   3.693s) [main thread     ]               main.cpp:205      0| Exit from application
> 2019-08-07 18:49:59.762 (   3.793s) [                ]               main.cpp:156    ERR| NetListener Exception:: Accept on socket returned NULL. errno=0; No error
> 2019-08-07 18:49:59.772 (   3.804s) [main thread     ]             loguru.hpp:1703     0| atexit
> 

Но в основном (и во все следующие и предыдущие разы) ничего необычного
т.е ошибки про сокет уже нет, а коррупция heap есть

> 019-08-07 18:55:27.369 (   8.503s) [                ]        JsonHandler.cpp:134      8| JsonHandler::Circle detected
> 2019-08-07 18:55:27.370 (   8.503s) [                ]        JsonHandler.cpp:150      8| JsonHandler::Popup
> 2019-08-07 18:55:27.370 (   8.503s) [                ]        JsonHandler.cpp:146      8| JsonHandler::Message
> 2019-08-07 18:55:27.370 (   8.503s) [                ]        JsonHandler.cpp:129      8| JsonHandler::End

В Release версии происходит краш временами (без сообщения ошибки детального), а временами - нет.

--------
Пробовал prebuilt exe для win - от старой версии, отсюда
https://github.com/kswaldemar/rewind-viewer/issues/23
rewindviewer_win_1_2_2
там нет краша при закрытии LocalRunner.py

**Comment by kswaldemar** [comment]
Кажется спустя 1,5 года концов уже не найдем, к тому же с момента версии 1.3 код был сильно переписан, и прошло несколько конкурсов.
Если будет повторяться на новой версии, то создавайте новый issue и обязательно разберемся
